jokes = [
    "I told my therapist I feel like nobody listens to me. She said 'next please'.",
    "My wife told me to stop impersonating a flamingo. I had to put my foot down.",
    "Why do programmers prefer dark mode? Light attracts bugs... and also their exes.",
    "I have a joke about trickle-down economics... but 99% of you won't get it.",
    "I'm on a seafood diet. I see food and I eat it... because therapy is expensive.",
    "Parallel lines have so much in common... it's a shame they'll never meet.",
    "I used to play piano by ear... now I just play badly and blame the piano.",
    "My therapist says I have a preoccupation with revenge... we'll see about that.",
    "I told my suitcases no vacation this year. Now I'm dealing with emotional baggage fees.",
    "Why was the belt arrested? Holding up pants... and identity theft.",
    "I'm terrified of elevators… so I'm taking steps to avoid them.",
    "What do you call fake spaghetti? An impasta who catfished me.",
    "Why did the scarecrow win an award? Outstanding in his field... unlike my LinkedIn.",
    "I would tell a time travel joke... but you didn't like it yesterday.",
    "My friend says I'm a know-it-all… I already knew he was jealous.",
    "Why don't programmers like nature? Too many bugs... zero merge resolution.",
    "I told my boss I needed a mental health day... 'take two, you're back Monday'.",
    "I asked my dog what's two minus two. He said nothing.",
    "Why do seagulls fly over the sea? If over the bay they'd be bagels.",
    "I told my wife to embrace her mistakes. She gave me a hug.",
    "I'm reading a book on anti-gravity. Impossible to put down... glued my hands.",
    "My wife said do lunges to stay in shape. Big step forward.",
    "Why don't scientists trust atoms? They make up everything... including excuses.",
    "I'm addicted to seaweed. Need to seek kelp.",
    "I told my wife her eyebrows too high. She looked surprised... blocked me.",
    "What do you call fake noodle? Impasta who unmatched me.",
    "Why did tomato turn red? Saw salad dressing... and my browser history.",
    "I used to be addicted to hokey pokey... turned myself around.",
    "I'm writing book on reverse psychology... don't buy it.",
    "Why do programmers hate nature? Bugs... Wi-Fi terrible.",
    "I have construction joke... still working on it.",
    "Girlfriend said stop singing 'I'm a Believer'... I saw her face.",
    "Why don't eggs tell jokes? Crack up... sue for damage.",
    "Told wife I want cremated. She said 'last thing I want'.",
    "Friends with 25 alphabet letters. Don't know y.",
    "Why golfer two pants? Hole in one... or coffee spill.",
    "Told computer need more RAM... 'buy dinner first'.",
    "Therapist: finish what start for peace. Finished chips + Netflix.",
    "Programmers mix Halloween/Christmas? Oct 31 == Dec 25.",
    "Asked North Korean friend how it was. Couldn't complain.",
    "Great at sleeping. Eyes closed.",
    "Why tell actors break leg? Play has cast.",
    "Wife like fine wine... better age. She said expired milk.",
    "Password last 8 pi digits... nobody guesses.",
    "Used to indecisive... not sure now.",
    "Bicycle fall over? Two-tired... like Monday me.",
    "Not lazy. Energy-saving mode.",
    "Chemistry joke... won't pass, too basic.",
    "Code doesn't work, no idea why. Code works, no idea why.",
    "Told wife millionaire. She said 'already are... excuses'.",
    "Skeletons no music church? No organs... rhythm.",
    "Asked librarian paranoia books. Whispered 'behind you'.",
    "Wife 'never listen'. Funny way start conversation.",
    "Not Batman... seen same room? Exactly.",
    "Scarecrow neurosurgeon? Outstanding brain field.",
    "Stepladder... real ladder left kid.",
    "Wife immature. Get out blanket fort.",
    "JavaScript broke? Lost prototypes.",
    "Anti-gravity book... stuck ceiling.",
    "Wife 'treat house hotel'. Leave tip.",
    "Eggs no jokes? Crack... blame chicken.",
    "Boss late traffic. 'Remote'. Exactly.",
    "Not short... concentrated awesome.",
    "Programmers notebook? Log something.",
    "Wife fantasize other men? No, look like you.",
    "Therapist write hate letters burn. No friends left.",
    "Tomato blush? Salad dressing... search history.",
    "Not lazy. Standby mode.",
    "Buried sea. Deep.",
    "Programmers beaches? Sand-boxes.",
    "Password 'incorrect'... computer says 'incorrect'.",
    "Not arguing. Passionately correct.",
    "Scarecrow award? Unemployment field.",
    "Construction joke... working.",
    "Wife fine wine. Headaches.",
    "Skeletons fight? No guts... therapist.",
    "Computer break... vacation ads guilt.",
    "Not Batman... case closed.",
    "Programmers cats? Nine lives... no conflicts.",
    "Wife salary joke? Never mind, not funny.",
    "Therapist let past go. Student loans.",
    "Bicycle drunk... last Friday.",
    "Not lazy. Power-saving forever.",
    "Why skeletons no fight? No guts... lawyer.",
    "Therapist 'nobody listens'. 'Next'.",
    "Wife flamingo impersonate. Foot down.",
    "Trickle-down joke... 99% no get. 1% bought punchline.",
    "Feelings can't cook... seafood diet.",
    "Motivation deadlines... never meet.",
    "Blame piano... play badly.",
    "Revenge preoccupation... plant dead.",
    "Baggage fees... emotional too.",
    "Belt arrested... tax evasion.",
    "Elevators... stairs hate.",
    "Impasta catfished.",
    "LinkedIn profile... scarecrow better.",
    "Time travel... yesterday no like.",
    "Google history jealous.",
    "Merge resolution zero.",
    "Mental day... Monday back.",
    "Dog two minus two. Nothing.",
    "Bay bagels.",
    "Embrace mistakes. Hug.",
    "Glued hands... anti-gravity.",
    "Lunges... step forward.",
    "Atoms excuses.",
    "Seek kelp.",
    "Eyebrows high... Instagram block.",
    "Unmatched date.",
    "Browser history tomato.",
    "Hokey pokey... turned around.",
    "Reverse psychology... don't buy."
]
